var theloai = [
    { "idTL": "1", "TenTL": "Sống đẹp", "ThuTu": "1", "AnHien": "1", "lang": "vi" },
    { "idTL": "2", "TenTL": "Sức khoẻ", "ThuTu": "2", "AnHien": "1", "lang": "vi" },
    { "idTL": "3", "TenTL": "Xã hội", "ThuTu": "1", "AnHien": "1", "lang": "vi" },
    { "idTL": "4", "TenTL": "Việc làm", "ThuTu": "4", "AnHien": "0", "lang": "vi" },
    { "idTL": "5", "TenTL": "Nghệ thuật sống", "ThuTu": "2", "AnHien": "0", "lang": "vi" },
    { "idTL": "6", "TenTL": "Thường thức ", "ThuTu": "6", "AnHien": "0", "lang": "vi" },
    { "idTL": "7", "TenTL": "Thư giãn", "ThuTu": "5", "AnHien": "0", "lang": "vi" },
    { "idTL": "8", "TenTL": "Thế giới", "ThuTu": "1", "AnHien": "1", "lang": "vi" },
    { "idTL": "9", "TenTL": "Health", "ThuTu": "1", "AnHien": "0", "lang": "en" },
    { "idTL": "10", "TenTL": "Travel", "ThuTu": "5", "AnHien": "0", "lang": "en" },
    { "idTL": "11", "TenTL": "Business", "ThuTu": "2", "AnHien": "0", "lang": "en" },
    { "idTL": "12", "TenTL": "LifeStyle & Living", "ThuTu": "3", "AnHien": "0", "lang": "en" },
    { "idTL": "13", "TenTL": "Entertainment ", "ThuTu": "4", "AnHien": "0", "lang": "en" },
    { "idTL": "14", "TenTL": "Thiên nhiên", "ThuTu": "8", "AnHien": "0", "lang": "vi" },
    { "idTL": "15", "TenTL": "Công nghệ", "ThuTu": "3", "AnHien": "1", "lang": "vi" },
    { "idTL": "16", "TenTL": "MỚI NHẬN", "ThuTu": "0", "AnHien": "0", "lang": "vi" },
    { "idTL": "17", "TenTL": "HOT", "ThuTu": "0", "AnHien": "0", "lang": "vi" },
]
